services:
- type: web
  name: gitpod-openvscode-server-example
  env: docker
  repo: https://github.com/EliasL-git/vscode-on-render.git
  autoDeploy: false
  envVars:
    - key: OPENVSCODE_CONNECTION_TOKEN
      generateValue: true
  disk:
    name: data
    mountPath: /home/workspace
    sizeGB: 1
